
# printing node versions

# name: print node version
# on:
#   push:
#     branches: [master]
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Install Node.js
#         uses: actions/setup-node@v2
#       - name: Print node version
#         run: node -v

# Running ESLint

# name: Run ESLint 
# on: 
#   push:
#     branches: [master] 
# jobs: 
#   build: 
#     runs-on: ubuntu-latest 
#     steps: 
#       - name: Checkout code
#         uses: actions/checkout@v2 
#       - name: Install Node.js 
#         uses: actions/setup-node@v2 
#       - name: Install dependencies 
#         run:  npm install eslint --save-dev
#       - name: Run ESLint 
#         run: npx eslint .